name: 'Cookie Notice'
version: '2.0.0'
description: 'This addon displays a cookie consent notice on your site.'
developer: Double Three Digital
developer_url: https://doublethree.digital
commercial: true
