fields:
  styles:
    type: toggle
  text:
    type: textarea
  location:
    options:
      bottom: 'Bottom of Screen'
      top: 'Top of Screen'
    type: select
    default: bottom
  dont-accept:
    type: toggle
