fields:
  text:
    type: textarea
  location:
    options:
      bottom: 'Bottom'
      top: 'Top'
    type: select
    default: bottom  
  technical_section:
    type: section
    display: Technical
  cookie-name:
    type: text
    default: 'cookie_notice'
    width: 50
  disable_styles:
    type: toggle
    width: 50